Repository icgc-argo/dac-ui, pull requests merged in 2021-08, with the labels that each got.

#343 🔖 rc 0.22.1
  components/pages/Applications/ApplicationForm/Forms/Collaborators/ErrorBanner.tsx
  components/pages/Applications/ApplicationForm/Forms/Collaborators/index.tsx
  components/pages/Applications/ApplicationForm/Forms/Terms.tsx
  components/pages/Applications/ApplicationForm/Forms/common.tsx
  components/pages/Applications/ApplicationForm/Forms/constants.tsx
  components/pages/Applications/ApplicationForm/Forms/validations/helpers.ts
  components/pages/Applications/ApplicationForm/Forms/validations/index.ts
  components/pages/Applications/Dashboard/Applications/Start.tsx
  components/pages/Applications/Dashboard/index.tsx
  components/pages/Applications/PDF/StaticIntroduction.tsx
  components/pages/Applications/PDF/StaticProjectInfo.tsx
  components/pages/Applications/PDF/StaticTerms.tsx
  components/pages/Applications/PDF/textConstants.ts
  components/pages/Home/index.tsx
  global/constants/externalPaths.ts
  package-lock.json
  package.json
Labels: 0.22.1

#359 🔖 rc 0.23.0
  .env.schema
  components/DefaultPageLayout.tsx
  components/Head.tsx
  components/NavBar.tsx
  components/Root.tsx
  components/pages/Applications/ApplicationForm/Forms/Applicant.tsx
  components/pages/Applications/ApplicationForm/Forms/EthicsLetter/UploadsTable.tsx
  components/pages/Applications/ApplicationForm/Forms/Representative.tsx
  components/pages/Applications/ApplicationForm/Forms/Signature.tsx
  components/pages/Applications/ApplicationForm/Forms/common.tsx
  components/pages/Applications/ApplicationForm/Forms/validations/helpers.ts
  components/pages/Applications/ApplicationForm/Forms/validations/index.ts
  components/pages/Applications/ApplicationForm/Forms/validations/schemas.ts
  components/pages/Applications/Dashboard/Applications/index.tsx
  components/pages/Applications/PDF/StaticTerms.tsx
  components/pages/Applications/index.tsx
  components/pages/Error/Generic.tsx
  components/pages/Error/Maintenance.tsx
  components/pages/Error/NotAllowed.tsx
  components/pages/Error/NotFound.tsx
  components/pages/Error/index.tsx
  components/pages/Home/index.tsx
  global/config/index.tsx
  global/constants/externalPaths.ts
  next.config.js
  package-lock.json
  package.json
  pages/403.tsx
  pages/404.tsx
  pages/_app.tsx
  pages/_error.tsx
  pages/logged-in.tsx
  pages/maintenance.tsx
  public/client-error.svg
  public/dna-broken.svg
  public/logomark.svg
  public/maintenance.svg
Labels: 0.23.0

#370 353 - update uikit
  package-lock.json
  package.json
Labels: 0.23.1

#368 🔖 rc 0.23.1
  components/pages/Applications/ApplicationForm/Forms/Signature.tsx
  components/pages/Applications/ApplicationForm/Forms/constants.tsx
  components/pages/Applications/ApplicationForm/Forms/index.tsx
  components/pages/Applications/ApplicationForm/Forms/validations/helpers.ts
  components/pages/Applications/ApplicationForm/Forms/validations/index.ts
  package-lock.json
  package.json
Labels: 0.23.1
