Repository icgc-argo/dac-ui, pull requests merged in 2021-07, with the labels that each got.

#185 🔖 rc 0.12.0
  components/pages/Applications/ApplicationForm/Forms/Outline/index.tsx
  components/pages/Applications/ApplicationForm/Forms/ProjectInfo/PublicationURLs.tsx
  components/pages/Applications/ApplicationForm/Forms/Representative.tsx
  components/pages/Applications/ApplicationForm/Forms/Terms.tsx
  components/pages/Applications/ApplicationForm/Forms/constants.tsx
  components/pages/Applications/ApplicationForm/Forms/helpers.tsx
  components/pages/Applications/ApplicationForm/Forms/types.ts
  components/pages/Applications/ApplicationForm/Forms/validations/helpers.ts
  components/pages/Applications/ApplicationForm/Forms/validations/index.ts
  components/pages/Applications/ApplicationForm/Forms/validations/schemas.ts
  components/pages/Applications/ApplicationForm/Header/Actions.tsx
  components/pages/Applications/Dashboard/Applications/InProgress/constants.ts
  components/pages/Applications/ManageApplications/utils.tsx
  components/pages/Applications/PDF/Cover.tsx
  components/pages/Applications/PDF/PdfLayout.tsx
  components/pages/Applications/PDF/Signatures.tsx
  components/pages/Applications/PDF/StaticApplicant.tsx
  components/pages/Applications/PDF/StaticCollaborators.tsx
  components/pages/Applications/PDF/StaticProjectInfo.tsx
  components/pages/Applications/PDF/StaticRepresentative.tsx
  components/pages/Applications/PDF/VerticalTable.tsx
  components/pages/Applications/PDF/common.tsx
  components/pages/Applications/PDF/types.ts
  components/pages/Applications/types.ts
  global/constants/externalPaths.ts
  package-lock.json
  package.json
Labels: 0.12.0

#270 🔖 rc 0.19.0
  Dockerfile
  components/pages/Applications/ApplicationForm/Forms/Collaborators.tsx
  components/pages/Applications/ApplicationForm/Forms/Collaborators/TableComponent.tsx
  components/pages/Applications/ApplicationForm/Forms/Collaborators/index.tsx
  components/pages/Applications/ApplicationForm/Forms/EthicsLetter/NoFilesMessage.tsx
  components/pages/Applications/ApplicationForm/Forms/EthicsLetter/UploadsTable.tsx
  components/pages/Applications/ApplicationForm/Forms/EthicsLetter/index.tsx
  components/pages/Applications/ApplicationForm/Forms/Signature.tsx
  components/pages/Applications/ApplicationForm/Forms/helpers.tsx
  components/pages/Applications/ApplicationForm/Forms/types.ts
  components/pages/Applications/ApplicationForm/Forms/validations/helpers.ts
  components/pages/Applications/ApplicationForm/Forms/validations/index.ts
  components/pages/Applications/ApplicationForm/Forms/validations/schemas.ts
  components/pages/Applications/types.ts
  global/hooks/useAuthContext.tsx
  package-lock.json
  package.json
Labels: 0.19.0

#277 🔖 rc 0.19.1
  components/NavBar.tsx
  components/pages/Applications/ApplicationForm/Forms/index.tsx
  components/pages/Applications/ApplicationForm/Forms/types.ts
  components/pages/Applications/ApplicationForm/Forms/validations/index.ts
  components/pages/Applications/ApplicationForm/Header/Actions.tsx
  package-lock.json
  package.json
Labels: 0.19.1

#310 🔖 rc 0.21.1
  components/pages/Applications/ApplicationForm/Forms/Collaborators/TableComponent.tsx
  components/pages/Applications/ApplicationForm/Forms/Collaborators/index.tsx
  components/pages/Applications/ApplicationForm/Forms/EthicsLetter/UploadsTable.tsx
  components/pages/Applications/ApplicationForm/Forms/EthicsLetter/index.tsx
  components/pages/Applications/ApplicationForm/Forms/validations/helpers.ts
  components/pages/Applications/ApplicationForm/Forms/validations/index.ts
  components/pages/Applications/ApplicationForm/Forms/validations/schemas.ts
  package-lock.json
  package.json
Labels: 0.21.1

#323 Rc/0.21.2
  components/pages/Applications/ApplicationForm/Forms/Applicant.tsx
  components/pages/Applications/ApplicationForm/Forms/Collaborators/index.tsx
  components/pages/Applications/ApplicationForm/Forms/EthicsLetter/UploadsTable.tsx
  components/pages/Applications/ApplicationForm/Forms/EthicsLetter/index.tsx
  components/pages/Applications/PDF/StaticApplicant.tsx
  components/pages/Applications/PDF/StaticCollaborators.tsx
  components/pages/Applications/PDF/StaticEthics.tsx
  components/pages/Applications/PDF/StaticProjectInfo.tsx
  components/pages/Applications/PDF/StaticRepresentative.tsx
  components/pages/Applications/PDF/textConstants.ts
  components/pages/Home/index.tsx
  package-lock.json
  package.json
  public/ICGC-ARGO-logo-FULL-white.svg
  public/ICGC-ARGO-logo-white.svg
  public/icgc-argo-logo-white.svg
Labels: 0.21.2
